cache:
  paths:
    - node_modules/

stages:
 - build
 - test
 - deploy

test:
  stage: test
  variables:
    NODE_ENV: 'production'
  tags:
    - development
  script:
    - npm run test
  only:
    - branches
    - tags
